services:
  tailscale-jellyfin:
    image: tailscale/tailscale:latest
    container_name: tailscale-jellyfin
    hostname: jellyfin
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    env_file:
      - path: ./.env.media-services
        required: true
    volumes:
      - tailscale-jellyfin:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: always

  # Running on port 8096
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    depends_on:
      - tailscale-jellyfin
    user: 1000:1000
    network_mode: service:tailscale-jellyfin
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - type: bind
        source: /mnt/Media
        target: /Media
        read_only: true
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin
    restart: always

volumes:
  jellyfin:
  tailscale-jellyfin:
